### ISSUE TITLE
Hướng dẫn build website local

### ISSUE THREAD

**Issue by quanhoang-pm** [MIMPython/mimpython.github.io#1]
Hướng dẫn build website local ở phiên bản hiện tại ([a948360](https://github.com/MIMPython/mimpython.github.io/commit/a948360569c7d326f7d12d2e8bec723331f4d0f9)) còn khó hiểu.

Đặc biệt, hướng dẫn cần phân biệt rõ đâu là những bước cài đặt chỉ cần thực hiện một lần và đâu là bước thực thi cần thực hiện mỗi lần build website.

@thanhtung1005 ước lượng thời gian thực hiện công việc này và phân công nhé.

**Comment by quanhoang-pm** [comment]
Khi chạy lệnh `bundle install` thì mình gặp lỗi sau
```txt
An error occurred while installing racc (1.6.0), and Bundler cannot continue.

In Gemfile:
  jekyll-algolia was resolved to 1.7.1, which depends on
    algolia_html_extractor was resolved to 2.6.4, which depends on
      nokogiri was resolved to 1.13.6, which depends on
        racc
```
Việc này có thể khắc phục như thế nào vậy @thanhtung1005 ?

**Comment by Tung-hehe** [comment]
Em đã tìm hiểu lỗi này và có vẻ như phiên bản ruby chưa được update. @quanhoang-pm  thử chạy câu lệnh:

```
sudo apt-get install ruby-full build-essential
```
Sau đó cài đặt lại bundle cho trang web thử xem ạ!

**Comment by quanhoang-pm** [comment]
Lệnh `bundle clean` có thực sự cần thiết không?

**Comment by Tung-hehe** [comment]
Lệnh `bundle clean` sẽ cần để gỡ bundle cũ để cài lại bundle mới ạ!

**Comment by quanhoang-pm** [comment]
@thanhtung1005 ghi phần update ruby lên README nhé.
