### ISSUE TITLE
Format file một cách tự động

### ISSUE THREAD

**Issue by quanhoang-pm** [MIMPython/mimpython.github.io#2]
Một số file hiện tại trong repo bị thừa dấu tab/cách ở các dòng trắng và thiếu dấu xuống dòng ở cuối file. Ở trong repository này, chúng ta sẽ thống nhất loại bỏ tất cả các dấu tab/cách thừa và đặt một dấu xuống dòng ở cuối file.

Chuyện này được thực hiện tự động ở một số text editor (ví dụ như atom), đồng thời cũng có thể cài đặt trong file config trong VScode.

@TranTuan2412 ghi lại ở đây hướng dẫn thực hiện trong VScode để mọi người tham khảo nhé.

**Comment by TranTuan2412** [comment]
File format convention
- No trailing spaces
- Exactly one new line at the end of files

Setup
- Hit Ctrl + Shift + P (or press F1)
- Type `Preferences: Open settings (JSON)`
- Add following lines to the setting file
```json
{
"files.trimTrailingWhitespace": true,
"files.trimFinalNewlines": true,
"files.insertFinalNewline": true,
}
```

@MIMPython/instructors em/mình xin gửi hướng dẫn về cách format file một cách tự động.
